[2025-05-20T15:31:29.325+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_elt_pipeline.extract_crypto_data scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T15:31:29.329+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_elt_pipeline.extract_crypto_data scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T15:31:29.329+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-20T15:31:29.338+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_crypto_data> on 2025-05-19 00:00:00+00:00
[2025-05-20T15:31:29.350+0000] {standard_task_runner.py:60} INFO - Started process 200 to run task
[2025-05-20T15:31:29.360+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_elt_pipeline', 'extract_crypto_data', 'scheduled__2025-05-19T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmp6n03lmvp']
[2025-05-20T15:31:29.372+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask extract_crypto_data
[2025-05-20T15:31:29.429+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-20T15:31:29.513+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_elt_pipeline.extract_crypto_data scheduled__2025-05-19T00:00:00+00:00 [running]> on host 0ae289dee64a
[2025-05-20T15:31:29.616+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='deepak' AIRFLOW_CTX_DAG_ID='crypto_elt_pipeline' AIRFLOW_CTX_TASK_ID='extract_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T00:00:00+00:00'
[2025-05-20T15:31:29.619+0000] {logging_mixin.py:188} INFO - [INFO] Starting complex CoinGecko extraction...
[2025-05-20T15:31:29.955+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved historical data for: bitcoin
[2025-05-20T15:31:32.073+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved metadata for: bitcoin
[2025-05-20T15:31:34.237+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved historical data for: ethereum
[2025-05-20T15:31:36.384+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved metadata for: ethereum
[2025-05-20T15:31:38.575+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved historical data for: solana
[2025-05-20T15:31:40.665+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved metadata for: solana
[2025-05-20T15:31:41.603+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-05-20T15:31:41.754+0000] {process_utils.py:131} INFO - Sending 15 to group 200. PIDs of all processes in the group: [200]
[2025-05-20T15:31:41.776+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 200
[2025-05-20T15:31:41.799+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-20T15:31:41.852+0000] {logging_mixin.py:188} INFO - [WARNING] Skipping solana due to error: Task received SIGTERM signal
[2025-05-20T15:31:42.022+0000] {logging_mixin.py:188} INFO - [ERROR] 'prices' key not found in response for ripple
[2025-05-20T15:31:42.023+0000] {logging_mixin.py:188} INFO - {
  "status": {
    "error_code": 429,
    "error_message": "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."
  }
}
[2025-05-20T15:31:42.023+0000] {logging_mixin.py:188} INFO - [WARNING] Skipping ripple due to error: "[ERROR] API response missing 'prices' for ripple"
[2025-05-20T15:31:42.092+0000] {logging_mixin.py:188} INFO - [ERROR] 'prices' key not found in response for cardano
[2025-05-20T15:31:42.093+0000] {logging_mixin.py:188} INFO - {
  "status": {
    "error_code": 429,
    "error_message": "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."
  }
}
[2025-05-20T15:31:42.093+0000] {logging_mixin.py:188} INFO - [WARNING] Skipping cardano due to error: "[ERROR] API response missing 'prices' for cardano"
[2025-05-20T15:31:42.164+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/etl_scripts/extract.py", line 101, in extract_data
    fetch_global_stats()
  File "/opt/airflow/etl_scripts/extract.py", line 68, in fetch_global_stats
    data = response.json()["data"]
KeyError: 'data'
[2025-05-20T15:31:42.191+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_elt_pipeline, task_id=extract_crypto_data, execution_date=20250519T000000, start_date=20250520T153129, end_date=20250520T153142
[2025-05-20T15:31:42.226+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task extract_crypto_data ('data'; 200)
[2025-05-20T15:31:42.268+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=200, status='terminated', exitcode=1, started='15:31:28') (200) terminated with exit code 1
[2025-05-20T15:31:42.274+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 143
[2025-05-20T15:31:42.323+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T21:31:06.088+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_elt_pipeline.extract_crypto_data scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T21:31:06.091+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_elt_pipeline.extract_crypto_data scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T21:31:06.092+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-20T21:31:06.097+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_crypto_data> on 2025-05-19 00:00:00+00:00
[2025-05-20T21:31:06.100+0000] {standard_task_runner.py:60} INFO - Started process 173 to run task
[2025-05-20T21:31:06.102+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_elt_pipeline', 'extract_crypto_data', 'scheduled__2025-05-19T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpxsduztff']
[2025-05-20T21:31:06.104+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask extract_crypto_data
[2025-05-20T21:31:06.115+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-20T21:31:06.134+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_elt_pipeline.extract_crypto_data scheduled__2025-05-19T00:00:00+00:00 [running]> on host eb07b9207670
[2025-05-20T21:31:06.171+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='deepak' AIRFLOW_CTX_DAG_ID='crypto_elt_pipeline' AIRFLOW_CTX_TASK_ID='extract_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T00:00:00+00:00'
[2025-05-20T21:31:06.172+0000] {logging_mixin.py:188} INFO - [INFO] Starting complex CoinGecko extraction...
[2025-05-20T21:31:06.365+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved historical data for: bitcoin
[2025-05-20T21:31:08.486+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved metadata for: bitcoin
[2025-05-20T21:31:10.635+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved historical data for: ethereum
[2025-05-20T21:31:12.783+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved metadata for: ethereum
[2025-05-20T21:31:15.018+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved historical data for: solana
[2025-05-20T21:31:17.115+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved metadata for: solana
[2025-05-20T21:31:19.210+0000] {logging_mixin.py:188} INFO - [ERROR] 'prices' key not found in response for ripple
[2025-05-20T21:31:19.211+0000] {logging_mixin.py:188} INFO - {
  "status": {
    "error_code": 429,
    "error_message": "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."
  }
}
[2025-05-20T21:31:19.211+0000] {logging_mixin.py:188} INFO - [WARNING] Skipping ripple due to error: "[ERROR] API response missing 'prices' for ripple"
[2025-05-20T21:31:19.282+0000] {logging_mixin.py:188} INFO - [ERROR] 'prices' key not found in response for cardano
[2025-05-20T21:31:19.283+0000] {logging_mixin.py:188} INFO - {
  "status": {
    "error_code": 429,
    "error_message": "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."
  }
}
[2025-05-20T21:31:19.283+0000] {logging_mixin.py:188} INFO - [WARNING] Skipping cardano due to error: "[ERROR] API response missing 'prices' for cardano"
[2025-05-20T21:31:19.344+0000] {logging_mixin.py:188} INFO - [ERROR] Global stats 'data' key missing. Full response:
[2025-05-20T21:31:19.344+0000] {logging_mixin.py:188} INFO - {
  "status": {
    "error_code": 429,
    "error_message": "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."
  }
}
[2025-05-20T21:31:19.345+0000] {logging_mixin.py:188} INFO - [INFO] CoinGecko extraction completed.
[2025-05-20T21:31:19.346+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-20T21:31:19.370+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=crypto_elt_pipeline, task_id=extract_crypto_data, execution_date=20250519T000000, start_date=20250520T213106, end_date=20250520T213119
[2025-05-20T21:31:19.441+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-20T21:31:19.464+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
